blog/urls.py
# # imports
# from django.urls import path
# from django.views.generic import TemplateView
#
# from skeleton import views
# from skeleton import api
# # End: imports -----------------------------------------------------------------
#
# app_name = 'skeleton'
#
# urlpatterns = [
#     # path(route, view, kwargs=None, name=None)
#     path('example/all/', views.AllExampleModels.as_view(), name="all_examplemodels"),
#     path('example/add/', views.AddExampleModel.as_view(), name="add_examplemodel"),
#     path('example/edit/<int:modelID>/', views.EditExampleModel.as_view(), name="edit_examplemodel"),
#     path('example/<int:modelID>/', views.ExampleModel.as_view(), name="view_examplemodel"),
#     path('forbidden/', TemplateView.as_view(template_name="skeleton/forbidden.html"), name='forbidden'),
#
# ]

events/urls.py
# imports
from django.urls import path

from events import views
# End: imports -----------------------------------------------------------------

app_name = 'events'

urlpatterns = [
    # path(route, view, kwargs=None, name=None)
    path('all/', views.AllEventsView.as_view(), name="all_events"),
    path('add/', views.AddEventView.as_view(), name="add_event"),
    path('<int:eventID>/', views.EventView.as_view(), name="event_view"),
    path('edit/<int:modelID>/', views.EditEventView.as_view(), name="edit_event"),
    path('signup/<int:modelID>/', views.EventSignup.as_view(), name="event_signup"),
]

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from . import views

from django.contrib.auth import get_user_model
User = get_user_model()



urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('forbidden/', TemplateView.as_view(template_name="main/forbidden.html"), name='forbidden'),
    path('admin/', admin.site.urls),
    # path('lyche/', include('lyche.urls')),
    # path('arrangementer/', include('events.urls')),
    # path('informasjon/', include('info.urls')),
    path('accounts/', include('accounts.urls')),
    # path('opptak/', include('recruitment.urls')),
    # path('lokaler/', include('premises.urls')),

    # path('api/users/', emil_api.ExtendedAPI.as_view(model=User), name="api_users"),
    # path('api/workouts/', emil_api.ExtendedAPI.as_view(model=emil_models.Workout), name="api_workouts"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
# imports
from django.db import models
from django.conf import settings
from django.utils import timezone

from main import base as main_base

# End: imports -----------------------------------------------------------------

# Intermediate model
class Participant(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False, blank=False, verbose_name="Bruker")
    event = models.ForeignKey('events.Event', on_delete=models.CASCADE, null=False, blank=False, verbose_name="Event")
    date_joined = models.DateTimeField(default=timezone.now, null=False, blank=False, verbose_name="Dato påmeldt")
    has_paid = models.BooleanField(default=False, verbose_name="Har betalt")

    class Meta:
        ordering = ['id']
        verbose_name = "Deltaker"
        verbose_name_plural = "Deltakere"

    def __str__(self):
        return f"Participant: {self.user}"

class Event(main_base.CustomBaseModel):
    title = models.CharField(max_length=140, null=True, blank=False, verbose_name="Tittel")
    place = models.CharField(max_length=140, null=True, blank=True, verbose_name="Sted")
    start = models.DateTimeField(null=True, blank=True, verbose_name="Start")
    end = models.DateTimeField(null=True, blank=True, verbose_name="Slutt")
    description = models.TextField(null=True, blank=True, verbose_name="Beskrivelse")
    facebook_url = models.URLField(null=True, blank=True)
    image_url = models.URLField(null=True, blank=True)


    # price = models.IntegerField(null=True, blank=True)

    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, through='events.Participant', blank=True, related_name="events", verbose_name="Påmeldte")


    class Meta:
        ordering = ['-start', 'title']
        verbose_name = "Event"
        verbose_name_plural = "Events"

    def __str__(self):
        return f"{self.title}"
        # return "{} ({})".format(self.getTitle(), self.getDate())

    def save(self, *args, **kwargs):
        return super(Event, self).save(*args, **kwargs)

events/forms.py
# imports
import json

from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth import get_user_model

from events import models as event_models

User = get_user_model()

# End: imports -----------------------------------------------------------------

DATE_FORMATS = [
    "%d-%m-%y", "%d-%m-%Y", # 26-02-97  26-02-1997
    "%d/%m/%y", "%d/%m/%Y", # 26/02/97  26/02/1997
    "%d:%m:%y", "%d:%m:%Y", # 26:02:97  26:02:1997
    "%d.%m.%y", "%d.%m.%Y", # 26.02.97  26.02.1997
    "%d,%m,%y", "%d,%m,%Y", # 26,02,97  26,02,1997

    "%d/%m-%y", "%d/%m-%Y", # 26/02-97  26/02-1997
    "%d %m %y", "%d %m %Y", # 26 02 97  26 02 1997
]

TIME_FORMATS = [
    '%H:%M',        # '14:30'
    '%H.%M',        # '14.30'
    '%H %M',        # '14 30'
]

MIN_FORMATS = [
    "%M"
]

class EventForm(forms.ModelForm):

    required_css_class = 'required font-bold'

    class Meta:
        model = event_models.Event
        fields = [
            'title',
            'place',
            'start',
            'end',
            'description',
            'facebook_url',
            'image_url',
            # 'earlybirds',
            # 'price',
            # 'earlybird_price',
        ]

    def __init__(self, *args, **kwargs):
        super(type(self), self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

        # self.fields['title'].widget.attrs.update({'placeholder': 'Tittel'})

        self.fields['start'].widget.attrs.update({'class': 'flatpickr form-control'})
        self.fields['end'].widget.attrs.update({'class': 'flatpickr form-control'})
        self.fields['description'].widget.attrs.update({'class': 'tinymce form-control'})
        # self.fields['start'].widget.format = "%H:%M"
        #
        # self.fields['date'].widget.attrs.update({'placeholder': 'dd.mm.yy'})
        # self.fields['date'].widget.format = "%d.%m.%y"
        #
        # self.fields['end'].widget.attrs.update({'placeholder': 'hh:mm'})
        # self.fields['end'].widget.format = "%H:%M"
        




class EventFilterForm(forms.Form):
    search = forms.CharField(required=False, label="Søk")
    tag = forms.ChoiceField(required=False)
    # tag = forms.ChoiceField(required=False)
    lead = forms.ChoiceField(required=False, label="Instruktør (lead)")
    # lead = forms.ChoiceField(required=False, label="Instruktør (lead)")
    follow = forms.ChoiceField(required=False, label="Instruktør (follow)")
    bulk = forms.IntegerField(required=False, label="Bolk")
    day = forms.IntegerField(required=False, label="Dag")
    semester_char = forms.CharField(required=False, label="Semester")

    def __init__(self, *args, **kwargs):
        super(type(self), self).__init__(*args, **kwargs)
        for field in self.fields:
            # pass
            self.fields[field].widget.attrs.update({'class': 'event-filter form-control'})

        self.fields['search'].widget.attrs.update({'placeholder': 'Søk på tittel...', 'autofocus': True})
        self.fields['semester_char'].widget.attrs.update({'placeholder': 'Eks: H2019, V2020',})

        # self.fields['tag'].choices = [(-1, '-----')]
        # self.fields['tag'].choices += [(tag.id, tag.title) for tag in song_models.Tag.getQueryset(["event"])]
        # self.fields['tag'].widget.attrs.update({'class': 'form-control event-filter'})

events/views.py
# imports
import os
import json
import datetime

from django.views import View
from django.db.models import Q
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse

from main import views as main_views
from events import forms as event_forms
from events import models as event_models
from accounts import models as account_models

from django.contrib.auth import get_user_model
User = get_user_model()

# End: imports -----------------------------------------------------------------

# Functions
def trace(x):
    print(json.dumps(x, indent=4, sort_keys=True))

# End: Functions ---------------------------------------------------------------

perms_add_event = [
    login_required,
    permission_required('events.add_event', login_url='forbidden')
]
@method_decorator(perms_add_event, name='dispatch')
class AddEventView(main_views.GenericAddModel):
    template = 'events/event_form.html'
    form_class = event_forms.EventForm
    redirect_name = 'events:all_events'
    #redirect_id = 'id'


editEvent_dec = [
    login_required,
    permission_required('events.change_event', login_url='forbidden')
]
class EditEventView(main_views.GenericEditModel):
    template = 'events/event_form.html'
    form_class = event_forms.EventForm
    redirect_name = 'events:event_view'
    redirect_id = 'id'
    model = event_models.Event



allEvents_dec = [
    login_required,
    # permission_required('events.view_event', login_url='forbidden')
]
@method_decorator(allEvents_dec, name='dispatch')
class AllEventsView(View):
    template = 'events/all_events.html'
    form = event_forms.EventFilterForm

    def get(self, request):
        events = event_models.Event.objects.all()
        form = self.form()
        return render(request, self.template, {'form': form, 'events': events})

    def post(self, request):
        events = event_models.Event.objects.all()
        form = self.form(data=request.POST)
        if form.is_valid():
            events = self.event_filter(form, events)
        return render(request, self.template, {'form': form, 'events': events})

    def event_filter(self, form, queryset):
        search = form.cleaned_data['search']
        tag = form.cleaned_data['tag'] or None
        lead = form.cleaned_data['lead'] or None
        follow = form.cleaned_data['follow'] or None
        bulk = form.cleaned_data['bulk']
        day = form.cleaned_data['day']
        semester_char = form.cleaned_data['semester_char']

        if search != "":
            queryset = queryset.filter(title__icontains=search)
        if tag:
            queryset = queryset.filter(tags__id=tag)
        if lead:
            queryset = queryset.filter(lead=lead)
        if follow:
            queryset = queryset.filter(follow=follow)
        if bulk:
            queryset = queryset.filter(bulk=bulk)
        if day:
            queryset = queryset.filter(day=day)
        if semester_char:
            queryset = queryset.filter(semester_char=semester_char)

        return queryset



event_dec = [
    login_required,
    # permission_required('events.view_event', login_url='forbidden')
]
@method_decorator(event_dec, name='dispatch')
class EventView(View):
    template = 'events/event_view.html'

    def get(self, request, eventID):
        event = event_models.Event.objects.get(id=eventID)
        return render(request, self.template, {'event': event})



signup_dec = [
    login_required,
    # permission_required('events.view_event', login_url='forbidden')
]
@method_decorator(signup_dec, name='dispatch')
class EventSignup(View):

    def post(self, request, modelID):
        event = event_models.Event.objects.get(id=modelID)
        p, created = event_models.Participant.objects.get_or_create(
            user=request.user,
            event=event,
        )

        return redirect("events:event_view", modelID)

events/templates/events/all_events.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Alle events{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static "events/event_styles.css" %}">

    <style media="screen">
        #btn-add-event {
            position: sticky;
            top: 3.6em;
            z-index: 5;
        }
        .event-banner-wrapper {
            max-height: 18vw;
            overflow-y: hidden;
        }
        .zoom {
            transition: transform .09s;
        }
        .zoom:hover {
            transform: scale(1.01); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
            /* background-color: rgba(255, 255, 255, 0.9); */
            filter: brightness(150%);
        }

    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'events:all_events' %}">Alle events</a></li>
{% endblock %}

{% block body %}
    <div class="body-wrapper">

        <div class="h1">
            Alle events
        </div>

        {% if perms.events.add_event %}
            <div id="btn-add-event" class="">
                <a class="btn btn-secondary text-light" href="{% url 'events:add_event' %}">
                    <i class="lni-plus"></i>
                    Legg til events
                </a>
            </div>
        {% endif %}



        <div class=" mt-2">

            {% for event in events %}
                    <div class="bg-blur rounded-xl border border-dark event-card cursor-pointer p-3 mb-4 zoom">

                        <input type="hidden" name="event-url" value="{% url 'events:event_view' event.id %}">

                        {% if event.image_url %}
                            <div class="event-banner-wrapper">
                                <img class="event-banner w-100" src="{{ event.image_url }}" alt="">
                            </div>
                        {% endif %}


                            <div class="row m-0 p-0">
                                <div class="col-md m-0 p-0">
                                    <div class="h2">{{ event.title }}</div>
                                    <div class=""><b>Dato</b>: {{ event.start | date:'l d. M Y' | default:'TBA' }}</div>
                                    <div class="">
                                        <b>Når</b>:
                                        {{ event.start | date:'H:i' | default:'TBA' }}
                                        {% if event.end %}
                                            - {{ event.end | date:'H:i' | default:'TBA' }}
                                        {% endif %}
                                    </div>
                                    <div class=""><b>Hvor</b>: {{ event.place }}</div>
                                </div>
                            </div>

                    </div>
            {% endfor %}

        </div>







    </div>
{% endblock %}

{% block scripts %}

    <script type="text/javascript">
        $(document).ready(function() {
            $('.event-card').click(function() {
                var url = $(this).find('input[name=event-url]').val();
                window.location.href = url;
            })
        });
    </script>
{% endblock scripts %}

events/templates/events/event_form.html
{% extends 'main/base.html' %}
{% block title %}Event{% endblock %}

{% load static %}

{% block head %}

    <link rel="stylesheet" href="{% static "events/event_styles.css" %}">

    <style media="screen">

    </style>
{% endblock %}


{% block body %}
    <div class="body-wrapper">

        <div class="">

            {% if modelID %}
                <div class="h2">
                    Rediger event:
                </div>
            {% else %}
                <div class="h2">
                    Opprett event:
                </div>
            {% endif %}

            {{ form.non_field_errors }}

            <form method="post">
                {% csrf_token %}

                <div class="row m-0">
                    <div class="col-md mx-1 p-0">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">{{ form.title.label }}</span>
                            </div>
                            {{ form.title }}
                        </div>
                    </div>
                    <div class="col-md mx-1 p-0">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">{{ form.place.label }}</span>
                            </div>
                            {{ form.place }}
                        </div>
                    </div>
                    <div class="text-danger">
                        {{ form.title.errors }}
                        {{ form.place.errors }}
                    </div>
                </div>

                <div class="row m-0">
                    <div class="col-md-4 mx-1 p-0 mt-3">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">{{ form.start.label }}</div>
                            </div>
                            {{ form.start }}
                            <div class="input-group-append">
                                <div class="btn btn-dark text-light clear-datetime" data-target="{{ form.start.auto_id }}">
                                    <i class="lni-close small"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mx-1 p-0 mt-3">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">{{ form.end.label }}</span>
                            </div>
                            {{ form.end }}
                            <div class="input-group-append" >
                                <div class="btn btn-dark text-light clear-datetime" data-target="{{ form.end.auto_id }}">
                                    <i class="lni-close small"></i>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="text-danger">
                        {{ form.start.errors }}
                        {{ form.end.errors }}
                    </div>
                </div>

                <div class="row m-0">
                    <div class="col-md mx-1 p-0 mt-3">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">{{ form.facebook_url.label }}</span>
                            </div>
                            {{ form.facebook_url }}
                        </div>
                    </div>
                    <div class="text-danger">
                        {{ form.end.facebook_url }}
                    </div>
                </div>

                <div class="row m-0">
                    <div class="col-md mx-1 p-0 mt-3">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">{{ form.image_url.label }}</span>
                            </div>
                            {{ form.image_url }}
                        </div>
                    </div>
                    <div class="text-danger">
                        {{ form.end.image_url }}
                    </div>
                </div>

                <div class="row m-0">
                    <div class="col-md-4 mt-4">
                        {% if form.instance.id %}
                            <a class="btn btn-dark btn-block text-light" href="{% url 'events:event_view' form.instance.id %}">Avbryt</a>
                        {% else %}
                            <a class="btn btn-dark btn-block text-light" href="{% url 'events:all_events' %}">Avbryt</a>
                        {% endif %}
                    </div>
                    <div class="col mt-4">
                        <button type="submit" class="btn btn-secondary btn-block text-light">Lagre</button>
                    </div>
                </div>
            </form>

        </div>
    </div> <!-- END: body-wrapper -->
{% endblock %}

{% block scripts %}

<script type="text/javascript">

    var tinymceConfig = {
        selector: "textarea.tinymce",
        plugins: 'advlist autoresize autosave codesample emoticons help lists print searchreplace tabfocus textpattern',
        menubar: 'file edit insert view format tools table help',
        toolbar: 'undo redo | fontselect | fontsizeselect | bold italic underline | forecolor | backcolor | removeformat | numlist bullist',
        min_height: 50,
        max_height: 600,
        toolbar_sticky: false,
        autosave_ask_before_unload: true,
        autosave_interval: "30s",
        autosave_prefix: "{path}{query}-{id}-",
        autosave_restore_when_empty: false,
        autosave_retention: "2m",
        tabfocus_elements: ":prev,:next",
        toolbar_items_size: "small",
    }

    tinymce.init(tinymceConfig);

    $(document).ready(function() {

        flatpickr(".flatpickr", {
            locale: "no",
            // altInput: true,
            // altFormat: "j F, Y  H:i",
            enableTime: true,
            dateFormat: "d.m.Y  H:i"
        });

        $('.clear-datetime').click(function() {
            var id = $(this).attr('data-target');
            $(`#${id}`).val("");
        })

    })
</script>
{% endblock scripts %}

events/templates/events/event_view.html
{% extends 'main/base.html' %}
{% block title %}{{ event.title }}{% endblock %}
{% load static %}

{% block head %}

    <link rel="stylesheet" href="{% static "events/event_styles.css" %}">

    <style media="screen">

    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'events:all_events' %}">Alle events</a></li>
    <li class="breadcrumb-item"><a href="{% url 'events:event_view' event.id  %}">{{ event.title }}</a></li>
{% endblock %}

{% block body %}

    <div class="body-wrapper m-0 p-2">

        <div class="row m-0 p-0">
            <div class="col m-0 p-0">
                <div class="h1">
                    {{ event.title }}
                </div>
            </div>
            <div class="col m-0 p-0">
                {% if perms.events.change_event %}
                    <a class="btn btn-dark text-light btn-sm float-right" href="{% url 'events:edit_event' event.id %}"><i class="lni-pencil"></i> Rediger</a>
                {% endif %}

            </div>
        </div>

        <div class="row m-0 p-0">
            <div class="col-md m-0 p-0">
                <div class="">
                    <!-- https://ourcodeworld.com/articles/read/555/how-to-format-datetime-objects-in-the-view-and-template-in-django -->
                    <!-- https://docs.djangoproject.com/en/dev/ref/templates/builtins/#date -->
                    <div class=""><b>Dato</b>: {{ event.start | date:'d. M Y (D)' | default:'TBA' }}</div>
                    <div class=""><b>Når</b>: {{ event.start | date:'H:i' | default:'TBA' }} - {{ event.end | date:'H:i' | default:'TBA' }}</div>
                    <div class=""><b>Hvor</b>: {{ event.place | default:'TBA' }}</div>
                    <div class="">
                        <b>Facebook event</b>:
                        {% if event.facebook_url %}
                            <a href="{{event.facebook_url }}">
                                {{ event.facebook_url | default:'TBA' }}
                            </a>
                        {% else %}
                            TBA
                        {% endif %}
                    </div>
                </div>
            </div>

        </div>

        <div class="row m-0">

            <div class="col-md p-0">
                {{ event.description }}
            </div>

            <div class="col-md-4 p-1">
                <div class="bg-info text-light rounded p-2">
                    {% if request.user not in event.participants.all %}
                    <div class="">
                        <div class="">
                            Du er ikke meldt på dette arrangementet
                        </div>
                        <form id="form-signup" class="form-signup" action="{% url 'events:event_signup' event.id %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-dark btn-sm" type="submit" name="button">Meld på</button>
                        </form>
                        <div class="small font-italic">
                            Obs: Du kan ikke melde deg av. Ta kontakt med styret hvis du vil melde deg av

                        </div>
                    </div>
                    {% else %}
                    <div class="">
                        Du er meldt på dette arrangementet :D
                    </div>
                    {% endif %}
                </div>
            </div>

        </div>

        {% if perms.events.view_participant %}
            <div class="mt-3">
                <div class="table-responsive rounded">
                    <table class="table table-sm table-hover table-striped table-dark rounded">
                        <thead>
                        <tr>
                            <th scope="col">Deltaker</th>
                            <th scope="col">Dato</th>
                            <th scope="col">Earlybird</th>
                            <th scope="col">Betalt</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for participant in event.participant_set.all %}
                        <tr>
                            <th scope="row">{{ participant.user }}</th>
                            <td>{{ participant.date_joined | date:'d.m.y H:i' }}</td>
                            <td>
                                {% if participant.is_earlybird %}
                                    <i class="lni-check-mark-circle text-success"></i>
                                {% else %}
                                    <i class="lni-circle-minus text-danger"></i>
                                {% endif %}
                            </td>
                            <td>
                                {% if participant.has_paid %}
                                    <i class="lni-check-mark-circle text-success"></i>
                                {% else %}
                                    <i class="lni-circle-minus text-danger"></i>
                                {% endif %}
                            </td>
                            {% if perms.events.change_participant %}
                                <td>
                                    <a class="a-primary" href="{% url 'admin:events_participant_change' participant.id %}">Rediger</a>
                                </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}



        <div class="mt-5">
            <div class="text-right font-italic small">
                <div class="">
                    Sist redigert av: {{ event.last_editor | default:'Ukjent' }} {{ event.last_edited | date:'(d. M Y - H:i)' }}
                </div>
                Opprettet av: {{ event.creator | default:'Ukjent' }} {{ event.created | date:'(d. M Y - H:i)' }}
            </div>
        </div>

    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $("#form-signup").submit(function() {
                return confirm("Er du sikker på at du vil melde deg på dette arrangementet?");
            })
        })
    </script>
{% endblock scripts %}