accounts/urls.py
# imports
from django.urls import path
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views


from accounts import views
from accounts import forms as account_forms
# End: imports -----------------------------------------------------------------

app_name = 'accounts' # Necessary for url naming. eg {% url 'accounts:signin' %}

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    # path('login/', views.LoginView.as_view(), name='login'),
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login2.html", form_class=account_forms.CustomAuthenticationForm), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),
    path('users/xlsx/', views.UsersXLSX.as_view(), name='users_xlsx'),

    #path('delete_user/', views.DeleteUserView.as_view(), name="delete_user"),



]

blog/urls.py
# # imports
# from django.urls import path
# from django.views.generic import TemplateView
#
# from skeleton import views
# from skeleton import api
# # End: imports -----------------------------------------------------------------
#
# app_name = 'skeleton'
#
# urlpatterns = [
#     # path(route, view, kwargs=None, name=None)
#     path('example/all/', views.AllExampleModels.as_view(), name="all_examplemodels"),
#     path('example/add/', views.AddExampleModel.as_view(), name="add_examplemodel"),
#     path('example/edit/<int:modelID>/', views.EditExampleModel.as_view(), name="edit_examplemodel"),
#     path('example/<int:modelID>/', views.ExampleModel.as_view(), name="view_examplemodel"),
#     path('forbidden/', TemplateView.as_view(template_name="skeleton/forbidden.html"), name='forbidden'),
#
# ]

events/urls.py
# imports
from django.urls import path

from events import views
# End: imports -----------------------------------------------------------------

app_name = 'events'

urlpatterns = [
    # path(route, view, kwargs=None, name=None)
    path('all/', views.AllEventsView.as_view(), name="all_events"),
    path('add/', views.AddEventView.as_view(), name="add_event"),
    path('<int:eventID>/', views.EventView.as_view(), name="event_view"),
    path('edit/<int:modelID>/', views.EditEventView.as_view(), name="edit_event"),
    path('signup/<int:modelID>/', views.EventSignup.as_view(), name="event_signup"),
]

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from . import views

from django.contrib.auth import get_user_model
User = get_user_model()



urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('forbidden/', TemplateView.as_view(template_name="main/forbidden.html"), name='forbidden'),
    path('admin/', admin.site.urls),
    # path('lyche/', include('lyche.urls')),
    # path('arrangementer/', include('events.urls')),
    # path('informasjon/', include('info.urls')),
    path('accounts/', include('accounts.urls')),
    # path('opptak/', include('recruitment.urls')),
    # path('lokaler/', include('premises.urls')),

    # path('api/users/', emil_api.ExtendedAPI.as_view(model=User), name="api_users"),
    # path('api/workouts/', emil_api.ExtendedAPI.as_view(model=emil_models.Workout), name="api_workouts"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/views.py
from django.views import View
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import models as auth_models

from accounts import models as account_models
# Create your views here.

class Home(View):
    template = 'main/home.html'

    def get(self, request):
        groups = auth_models.Group.objects.all()
        departments = account_models.Department.objects.all()
        return render(request, self.template, {
            'groups': groups,
            'departments': departments,
        })


class GenericAddModel(View):
    template = "main/generic_form.html"
    form_class = None # (*) Required
    redirect_name = None # (*)
    redirect_id = None
    success_msg = "Lagringen var vellykket!"
    error_msg = "Lagringen var misslykket!"
    debug = 0 # [0, 1, 2, 3] higher lvl equals more detailed debug
    _cn = None

    def __init__(self, *args, **kwargs):
        super(View, self).__init__(*args, **kwargs)
        self._cn = self.__class__.__name__

        if not self.form_class:
            raise RuntimeError("Attribute 'form_class' is required")
        if not self.redirect_name:
            raise RuntimeError("Attribute 'redirect_name' is required")

        if self.debug >= 1:
            print(f"== debug: activated from {self._cn} ==")
        if self.debug >= 2:
            print(f"== __init__: form_class = {self.form_class.__name__}")
            print(f"== __init__: template = {self.template}")
            print(f"== __init__: redirect_name = {self.redirect_name}")
            print(f"== __init__: redirect_id = {self.redirect_id}")
            print(f"== __init__: success_msg = {self.success_msg}")
            print(f"== __init__: error_msg = {self.error_msg}")

    def get(self, request):
        form = self.form_class()
        return render(request, self.template, {'form': form})

    def post(self, request, form=None):
        if not form:
            form = self.form_class(request.POST, request.FILES)

        if self.debug >= 1:
            print(f"== {self._cn}.post: form = {form.data}\n\n")
            print(f"== {self._cn}.post: form.is_valid() = {form.is_valid()}")

        if form.is_valid():
            obj = form.save(commit=False)

            try:
                obj.creator = request.user
            except Exception as e:
                if self.debug >= 2: print(e)

            try:
                obj.created = timezone.now()
            except Exception as e:
                if self.debug >= 2: print(e)

            try:
                obj.last_editor = request.user
            except Exception as e:
                if self.debug >= 2: print(e)


            try:
                obj.last_edited = timezone.now()
            except Exception as e:
                if self.debug >= 2: print(e)

            # Save
            obj.save()

            try:
                form.save_m2m()
            except Exception as e:
                if self.debug >= 2: print(e)

            messages.success(request, self.success_msg)

            if self.redirect_id:
                return redirect(self.redirect_name, getattr(obj, self.redirect_id))
            else:
                return redirect(self.redirect_name)
        else:
            messages.error(request, self.error_msg)
            return render(request, self.template, {'form': form})


class GenericEditModel(GenericAddModel):
    model = None # Required

    def __init__(self, *args, **kwargs):
        super(GenericAddModel, self).__init__(*args, **kwargs)

        if not self.model:
            raise RuntimeError("Attribute 'model' is required")

    def get(self, request, modelID):
        instance = self.model.objects.get(id=modelID)
        form = self.form_class(instance=instance)
        return render(request, self.template, {'form': form, 'modelID': modelID})

    def post(self, request, modelID):
        instance = self.model.objects.get(id=modelID)
        form = self.form_class(request.POST, request.FILES, instance=instance)
        return super().post(request, form)








        # if form.is_valid():
        #     instance = form.save(commit=False)
        #     try:
        #         instance.last_editor = request.user
        #         instance.last_edited = timezone.now()
        #     except Exception as e:
        #         print(e)
        #     finally:
        #         instance.save()
        #
        #     messages.success(request, self.success_msg)
        #
        #     if self.redirect_id:
        #         return redirect(self.redirect_name, getattr(instance, self.redirect_id))
        #     else:
        #         return redirect(self.redirect_name)
        # else:
        #     messages.error(request, self.error_msg)
        #     return render(request, self.template, {'form': form, 'modelID': modelID})

main/templates/main/navbar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/navbar.css' %}"/>

<!-- Navbar -->
<nav id="nav" class="navbar navbar-expand-md navbar-dark fixed-top m-0 p-1">

    <a class="navbar-brand ml-2" href="{% url 'home' %}">
        <img id="logo" width="50" src='{% static "main/img/mg-150x150.png" %}' alt="">
        <span class="d-none d-sm-none d-md-inline">
            MG's internside
        </span>
    </a>

    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse mr-auto">
        <ul class="navbar-nav mr-auto ml-3">

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="distance-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Events
                </a>
                <div class="dropdown-menu bg-dark" aria-labelledby="distance-dropdown" style="">
                    <a class="dropdown-item text-light" href="{% url 'events:all_events' %}">Alle events</a>
                    <a class="dropdown-item text-light" href="{% url 'events:add_event' %}">Opprett events</a>
                    <!--
                    <a class="dropdown-item text-light" href="">Resultater</a>
                    <a class="dropdown-item text-light" href="">Statistikk</a>
                    -->
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="distance-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Wiki
                </a>
                <div class="dropdown-menu bg-dark" aria-labelledby="distance-dropdown" style="">
                    <a class="dropdown-item text-light" href="{% url 'wiki:dashboard' %}">Dashboard</a>
                    <a class="dropdown-item text-light" href="{% url 'wiki:add_folder' %}">Opprett mappe</a>
                    <a class="dropdown-item text-light" href="{% url 'wiki:add_page' %}">Opprett side</a>
                    <!--
                    <a class="dropdown-item text-light" href="">Resultater</a>
                    <a class="dropdown-item text-light" href="">Statistikk</a>
                    -->
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="distance-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Galleri
                </a>
                <div class="dropdown-menu bg-dark" aria-labelledby="distance-dropdown" style="">
                    <a class="dropdown-item text-light" href="{% url 'gallery:all_quotations' %}">Alle sitater</a>
                    <a class="dropdown-item text-light" href="{% url 'gallery:add_quotation' %}">Legg til sitat</a>
                    <a class="dropdown-item text-light" href="{% url 'gallery:favorite_quotations' %}">Dine favoritt sitater</a>
                    <a class="dropdown-item text-light" href="{% url 'gallery:all_uploads' %}">Alle opplastninger</a>
                    <a class="dropdown-item text-light" href="{% url 'gallery:upload' %}">Last opp fil/bilde</a>
                    <!--
                    <a class="dropdown-item text-light" href="">Resultater</a>
                    <a class="dropdown-item text-light" href="">Statistikk</a>
                    -->
                </div>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto mr-4">

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'accounts:profile' %}">
                        <i class="lni-user"></i>
                        {{ user }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">
                        <i class=""></i>
                        Logg ut
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        <i class=""></i>
                        Logg inn
                    </a>
                </li>
            {% endif %}


        </ul>
    </div>
</nav> <!-- End: navbar -->

main/templates/main/navbar_dev.html
<!-- Navbar -->
{% load static %}
<nav style="padding: 0px 0px 0px 20px; box-shadow: 0 8px 10px -10px #010101; -webkit-box-shadow: 0 8px 10px -10px #010101; background-color: #0d0d0d;" class="navbar navbar-expand-lg navbar-dark fixed-top">

    <a style="padding: 0px; margin: 0px 50px 0px 0px" class="navbar-brand" href="{% url 'stefan:index' %}">
        <img style="padding: 0px 0px 0px 10px" width="60" src="{% static "main/Forsvarets_merke.png" %}" alt="">
        Idretten Ørland Flystasjon
    </a>



    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div id="navbar" class="collapse navbar-collapse mr-auto">
        <ul class="navbar-nav mr-auto">


            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">
                    {# <img src="https://img.icons8.com/ios/24/FFFFFF/69.png"> #}
                    {# <i class="lni-timer"></i> #}
                    <i class="lni-calendar"></i>
                    Adminpanel
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="distance-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Distance
                </a>
                <div class="dropdown-menu" aria-labelledby="distance-dropdown">
                    <a class="dropdown-item" href="{% url 'distance:register' %}">Registrer økt</a>
                    <a class="dropdown-item" href="{% url 'distance:results' %}">Resultater</a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'distance:register' %}">
                    {# <img src="https://img.icons8.com/ios/24/FFFFFF/69.png"> #}
                    {# <i class="lni-timer"></i> #}
                    <i class="lni-calendar"></i>
                    Registrer
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="emil-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Emil
                </a>
                <div class="dropdown-menu" aria-labelledby="emil-dropdown">
                    <a class="dropdown-item" href="{% url 'emil:register' %}">Registrer økt</a>
                    <a class="dropdown-item" href="{% url 'emil:results' %}">Resultater</a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'stefan:register' %}">
                    <i class="lni-calendar"></i>
                    Stefan
                </a>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto">

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">
                        <i class="lni-calendar"></i>
                        {{ user }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">
                        <i class="lni-calendar"></i>
                        Logg ut
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        <i class="lni-calendar"></i>
                        Logg inn
                    </a>
                </li>
            {% endif %}


        </ul>
    </div>
</nav> <!-- End: navbar -->

main/templates/main/recursive_departments.html
{# Show only folder if folder and user perms match #}
{# {% if folder.perm and folder.perm in request.user.user_permissions.all or not folder.perm or request.user.is_superuser %} #}

    <div class="">

        <div class="menu-item m-1 cursor-default" data-toggle="collapse" data-target="#{{ folder.title }}-collapsible">
            <i class="lni lni-chevron-down"></i>
            <i class="lni lni-chevron-up d-none"></i>
            <span class="h6">{{ folder.title }}:</span>
        </div>


        <div id="{{ folder.title }}-collapsible" class="border-left border-info pl-2 ml-2 collapse show">

            {% for ch in folder.children.all %}
                {% with folder=ch template_name="wiki/tree_structure.html" %}

                    {% include template_name %}

                {% endwith %}
            {% endfor %}

            <div class="">
                {% for page in folder.pages.all %}
                    <div class="">
                        <a href="{% url 'wiki:page_view' page.id %}">{{ page.title | truncatechars:30 }}</a>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>

{# {% endif %} #}